### ISSUE TITLE
Actually show me the install script

### ISSUE THREAD

**Issue by djc** [AsahiLinux/AsahiLinux.github.io#28]
You advertise that I install Asahi with `curl https://alx.sh | sh`. Shortly after starting, this presents me with a sudo prompt. If I then go to check out what the hell I'm actually running by opening https://alx.sh in my browser, I'm presented with a nice human-friendly site instead of a shell script. This makes it harder for me to audit what the installer is going to be running.

**Comment by svenpeter42** [comment]
```
curl https://alx.sh
cat alx.sh
sh alx.sh
```

Otherwise it's this script here: https://github.com/AsahiLinux/asahi-installer/blob/main/scripts/bootstrap-prod.sh

**Comment by marcan** [comment]
I'm curious, what is your motivation for auditing the code? Is it security, looking for backdoors, potential bugs, something else?

I would generally expect folks who plan to audit our installer to have no trouble coming up with `curl https://alx.sh > alx.sh`. The user-friendly redirect is there precisely for less experienced users who might not understand how this works and might end up clicking the link (e.g. if someone posted the curl command in a medium with auto-linkification).

**Comment by djc** [comment]
@marcan in some sense it is security, although I wouldn't have gone very deep. I'd just like to get a general sense of what kinds of things the script would be doing.

Redirecting the `curl` output would certainly have been an option, I think other things being equal I'd rather look at code in my browser than in my terminal or a terminal editor these days.

My point against the user-friendly redirect is that it sort of obfuscates what is going on. Even for less experienced users, I'm not sure redirecting them from what's supposed to contain an installer script to just the homepage of the project is the best solution (though it's certainly an expedient one), which makes the process more opaque rather than easier to understand.

Depending on how much effort you want to spend here, maybe the positive-sum solution is to have a landing page on the website that either links to the installer script on GitHub or has an inline copy of the installer script (for bonus points, with some syntax highlighting) below some contextual information for less experienced users.

**Comment by marcan** [comment]
The "installer script" is just a 55-line bootstrap script that downloads and runs a tarball that includes another script and a full Python runtime and ~2400 lines of bespoke Python code from asahi-installer.

I really don't understand this "I want to audit the code" reaction; it seems people only have it when you tell them to run `curl | sh`. Nobody is telling Ubuntu to post a link to their installer source code (whatever that means, since it's a lot of moving parts) next to their .iso downloads). Nobody is telling GIMP that their .exe download for Windows is not auditable.

At the end of the day, either you trust us or you don't. And if you don't, well, your only option is to take all of our code from GitHub, audit it, and build it yourself. Looking at the 55-line shell script that kicks off a full OS install in your browser isn't going give you any assurances; that's just security theatre.

Plus, of course, if your concern is active malice, using the browser isn't actually useful; as the redirect demonstrates, it's trivial to serve different content to it and to curl. If anything, the current behavior educates people who think they know how to audit curl|sh setups that their approach is broken :-)
